import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { AuthProvider } from "../context/AuthContext";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { EthereumProvider } from "@/context/WalletContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          {/* <header
            style={{
              padding: "1rem",
              borderBottom: "1px solid #eee",
              marginBottom: "2rem"
            }}
          >
            <nav style={{ display: "flex", gap: "1rem" }}>
              <Link href="/login">Login</Link>
              <Link href="/register">Register</Link>
              <Link href="/consent">Consent</Link>
              <Link href="/credentials">Credentials</Link>
            </nav>
          </header> */}
          <Navbar />
          <EthereumProvider>{children}</EthereumProvider>

          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
